version: 2
jobs:
  build:
  working_directory: /go/src/github.com/yu19991013/CircleCi-go-test
  docker:
    - image: circleci/golang:1.11.0
    environment:
          GO111MODULE: "on"
  steps:
    - checkout
    - restore_cache:
          name: Restore go modules cache
          keys:
            - mod-{{ .Environment.COMMON_CACHE_KEY }}-{{ checksum "go.mod" }}
    - run:
          name: Vendoring
          command: go mod download
      - save_cache:
          name: Save go modules cache
          key: mod-{{ .Environment.COMMON_CACHE_KEY }}-{{ checksum "go.mod" }}
          paths:
            - /go/pkg/mod/cache
    - run:
    name: Run tests
    command: go test ./...

  